 
		           -- Pizza Sales
        
/*   Questions  */
 
 
 /* 1. Retrive the total number of order placed. */
/* 2. Calculate the total revenue generated from pizza sales. */
/* 3. Calculate the total revenue generated from pizza sales using pizza price and quantity sold. */
/* 4. Identify the most expensive pizza by displaying its name, size, and price. */
/* 5. Determine which pizza size is ordered the most by customers based on total quantity sold. */
/* 6. Calculate the total number of pizzas sold for each pizza category such as Classic, Veggie, Supreme, etc. */
/* 7. Calculate the total revenue generated by each pizza category. */
/* 8. Identify the top five most ordered pizzas based on the total quantity sold. */
/* 9. Analyze daily order trends by calculating the total number of orders placed on each date. */
/* 10. Analyze customer ordering behavior by identifying the hour of the day with the highest number of orders. */
/* 11. Calculate the percentage contribution of each pizza type to total revenue. */
/* 12. Analyze the cumulative revenue over the time. */


/* Q1. Retrive the total number of order placed. */

   SELECT 
    COUNT(order_id)
FROM
    orders;

/* Q2. Calculate the total revenue generated from pizza sales. */

SELECT 
    SUM(quantity) AS total_pizza_sold
FROM
    order_details;

/* Q3. Calculate the total revenue generated from pizza sales using pizza price and quantity sold. */

SELECT 
    ROUND(SUM(order_details.quantity * pizzas.price),
            2) AS total_revenue
FROM
    order_details
        JOIN
    pizzas ON pizzas.pizza_id = order_details.pizza_id;

/* Q4. Identify the most expensive pizza by displaying its name, size, and price. */

SELECT 
    pizza_types.name, pizzas.size, pizzas.price
FROM
    pizza_types
        JOIN
    pizzas ON pizza_types.pizza_type_id = pizzas.pizza_type_id
ORDER BY pizzas.price DESC
LIMIT 1;

/* Q5. Determine which pizza size is ordered the most by customers based on total quantity sold. */

SELECT 
    pizzas.size, SUM(order_details.quantity) AS total_quantity
FROM
    order_details
        JOIN
    pizzas ON order_details.pizza_id = pizzas.pizza_id
GROUP BY pizzas.size
ORDER BY total_quantity DESC
LIMIT 1;

/* Q6. Calculate the total number of pizzas sold for each pizza category such as Classic, Veggie, Supreme, etc. */

SELECT 
    pizza_types.category,
    SUM(order_details.quantity) AS total_quantity
FROM
    order_details
        JOIN
    pizzas ON order_details.pizza_id = pizzas.pizza_id
        JOIN
    pizza_types ON pizzas.pizza_type_id = pizza_types.pizza_type_id
GROUP BY pizza_types.category;

/* Q7. Calculate the total revenue generated by each pizza category. */

SELECT 
    pizza_types.category,
    SUM(order_details.quantity * pizzas.price) AS total_revenue
FROM
    order_details
        JOIN
    pizzas ON order_details.pizza_id = pizzas.pizza_id
        JOIN
    pizza_types ON pizza_types.pizza_type_id = pizzas.pizza_type_id
GROUP BY pizza_types.category;

/* Q8. Identify the top five most ordered pizzas based on the total quantity sold. */

SELECT 
    pizza_types.name,
    SUM(order_details.quantity) AS most_ordered
FROM
    order_details
        JOIN
    pizzas ON order_details.pizza_id = pizzas.pizza_id
        JOIN
    pizza_types ON pizzas.pizza_type_id = pizza_types.pizza_type_id
GROUP BY pizza_types.name
ORDER BY most_ordered DESC
LIMIT 5;

/* Q9. Analyze daily order trends by calculating the total number of orders placed on each date. */

SELECT 
    orders.order_date, COUNT(orders.order_id) AS total_orders
FROM
    orders
GROUP BY orders.order_date
ORDER BY orders.order_date;

/* Q10. Analyze customer ordering behavior by identifying the hour of the day with the highest number of orders. */

SELECT 
    HOUR(orders.order_time) AS total_hour,
    COUNT(orders.order_id) AS total_order
FROM
    orders
GROUP BY orders.order_time
ORDER BY total_order DESC
LIMIT 1;

/* Q11. Calculate the percentage contribution of each pizza type to total revenue. */

SELECT 
    pizza_types.category,
    (SUM(order_details.quantity * price) / (SELECT 
            ROUND(SUM(order_details.quantity * pizzas.price),
                        2) AS total_sales
        FROM
            order_details
                JOIN
            pizzas ON pizzas.pizza_id = order_details.pizza_id) * 100 , 2) AS revenue
FROM
    pizza_types
        JOIN
    pizzas ON pizza_types.pizza_type_id = pizzas.pizza_type_id
        JOIN
    order_details ON order_details.pizza_id = pizzas.pizza_id
GROUP BY pizza_types.category
ORDER BY revenue DESC;

/* Q12. Analyze the cumulative revenue over the time. */

SELECT order_date,
SUM(revenue) over(order by order_date) as cum_revenue
from
(SELECT orders.order_date, 
SUM(order_details.quantity * pizzas.price) AS revenue
FROM order_details join pizzas
on order_details.pizza_id = pizzas.pizza_id
JOIN 
orders on orders.order_id = order_details.order_id
GROUP by orders.order_date) as sales;
